apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: rookies5-macta-ssm
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-2
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rookies5-macta-backend-secret
  namespace: rookies5-macta
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rookies5-macta-ssm
    kind: ClusterSecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_URL
      remoteRef:
        key: /rookies5-macta/dev/backend/DB_URL
    - secretKey: DB_USERNAME
      remoteRef:
        key: /rookies5-macta/dev/backend/DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteRef:
        key: /rookies5-macta/dev/backend/DB_PASSWORD
    - secretKey: S3_BUCKET_NAME
      remoteRef:
        key: /rookies5-macta/dev/backend/S3_BUCKET_NAME
    - secretKey: AWS_REGION
      remoteRef:
        key: /rookies5-macta/dev/backend/AWS_REGION
    - secretKey: JWT_SECRET
      remoteRef:
        key: /rookies5-macta/dev/backend/JWT_SECRET
    - secretKey: REDIS_HOST
      remoteRef:
        key: /rookies5-macta/dev/backend/REDIS_HOST
    - secretKey: REDIS_PORT
      remoteRef:
        key: /rookies5-macta/dev/backend/REDIS_PORT
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: /rookies5-macta/dev/backend/REDIS_PASSWORD
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rookies5-macta-infra-config
  namespace: rookies5-macta
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: rookies5-macta-ssm
    kind: ClusterSecretStore
  target:
    name: rookies5-macta-infra-config
    creationPolicy: Owner
  data:
    - secretKey: BACKEND_ROLE_ARN
      remoteRef:
        key: /rookies5-macta/dev/infra/BACKEND_ROLE_ARN
    - secretKey: WAF_WEB_ACL_ARN
      remoteRef:
        key: /rookies5-macta/dev/infra/WAF_WEB_ACL_ARN
    - secretKey: ACM_CERTIFICATE_ARN
      remoteRef:
        key: /rookies5-macta/dev/infra/ACM_CERTIFICATE_ARN
