apiVersion: apps/v1
kind: Deployment
metadata:
  name: rookies5-macta-frontend
  namespace: rookies5-macta
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rookies5-macta-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: rookies5-macta-frontend
    spec:
      containers:
        - name: frontend
          image: 105588835975.dkr.ecr.ap-northeast-2.amazonaws.com/rookies5-macta/frontend:5db8b905166bdc0d1ec2bae1082da35e4bbdecbe
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 30
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: rookies5-macta-frontend-service
  namespace: rookies5-macta
spec:
  type: ClusterIP
  selector:
    app: rookies5-macta-frontend
  ports:
    - port: 80
      targetPort: 80
